openapi: 3.1.0
info:
  title: Keycloak Backend Device Enrollment API
  version: 0.2.1
  description: |
    Server-to-server API implemented by the backend and called by Keycloak.
    Covers the streamlined device enrollment workflow that supports the device-public-key-login
    endpoint and device lookup helpers used by the remaining grant flow.
servers:
  - url: https://backend.example.com
    description: Backend base URL

tags:
  - name: enrollment
  - name: users
  - name: devices

paths:
  /v1/enrollments/bind:
    post:
      tags: [ enrollment ]
      summary: Bind an enrolled device key to a user
      security:
        - KCSignature: [ ]
      description: |
        Called when Keycloak has identified/created the user and is ready to persist.
        Backend should atomically bind (device_id,jkt) to user_id and store public key material.
        If already bound to the same user, should be idempotent.
      operationId: enrollmentBind
      parameters:
        - $ref: '#/components/parameters/IdempotencyKey'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/EnrollmentBindRequest'
      responses:
        '200':
          description: Bound (idempotent)
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/EnrollmentBindResponse'
        '409':
          description: Device already bound to a different user
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '400':
          $ref: '#/components/responses/BadRequest'
        '401':
          $ref: '#/components/responses/Unauthorized'


  /v1/users:
    post:
      tags: [ users ]
      summary: Create a user
      security:
        - KCSignature: [ ]
      description: |
        Creates a backend user record that is used by Keycloak user-storage SPI.
      operationId: createUser
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UserUpsertRequest'
      responses:
        '201':
          description: Created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserRecord'
        '400':
          $ref: '#/components/responses/BadRequest'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '409':
          description: Conflict (e.g., duplicate username/email)
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

  /v1/users/{user_id}:
    get:
      tags: [ users ]
      summary: Get user by id
      operationId: getUser
      security:
        - KCSignature: [ ]
      parameters:
        - name: user_id
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: User
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserRecord'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '404':
          $ref: '#/components/responses/NotFound'

    put:
      tags: [ users ]
      summary: Update user by id
      operationId: updateUser
      security:
        - KCSignature: [ ]
      parameters:
        - name: user_id
          in: path
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UserUpsertRequest'
      responses:
        '200':
          description: Updated
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserRecord'
        '400':
          $ref: '#/components/responses/BadRequest'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '404':
          $ref: '#/components/responses/NotFound'

    delete:
      tags: [ users ]
      summary: Delete user by id
      operationId: deleteUser
      security:
        - KCSignature: [ ]
      parameters:
        - name: user_id
          in: path
          required: true
          schema:
            type: string
      responses:
        '204':
          description: Deleted
        '401':
          $ref: '#/components/responses/Unauthorized'
        '404':
          $ref: '#/components/responses/NotFound'

  /v1/users/search:
    post:
      tags: [ users ]
      summary: Search users by fields and attributes
      security:
        - KCSignature: [ ]
      description: |
        Supports exact/general search plus custom user attributes.
      operationId: searchUsers
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UserSearchRequest'
      responses:
        '200':
          description: Search results
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserSearchResponse'
        '400':
          $ref: '#/components/responses/BadRequest'
        '401':
          $ref: '#/components/responses/Unauthorized'

  /v1/devices/lookup:
    post:
      tags: [ devices ]
      summary: Lookup device binding by device_id and/or jkt
      security:
        - KCSignature: [ ]
      description: |
        Useful for custom grant: device_id/jkt -> user_id + public key material.
      operationId: lookupDevice
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/DeviceLookupRequest'
      responses:
        '200':
          description: Lookup result
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DeviceLookupResponse'
        '404':
          $ref: '#/components/responses/NotFound'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '400':
          $ref: '#/components/responses/BadRequest'

components:
  securitySchemes:
    KCSignature:
      type: apiKey
      in: header
      name: X-KC-Signature
  parameters:
    IdempotencyKey:
      name: Idempotency-Key
      in: header
      required: false
      schema:
        type: string
      description: |
        If provided, backend should ensure repeated calls with the same key are idempotent.

  responses:
    BadRequest:
      description: Bad request
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
    Unauthorized:
      description: Unauthorized
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
    NotFound:
      description: Not found
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
    TooManyRequests:
      description: Rate limited
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'

  schemas:
    EnrollmentBindRequest:
      type: object
      required: [ realm, client_id, user_id, device_id, jkt, public_jwk ]
      properties:
        realm:
          type: string
        client_id:
          type: string
        user_id:
          type: string
          description: Keycloak internal user id
        user_hint:
          type: string
          description: Optional username (e.g., phone E.164)
        device_id:
          type: string
        jkt:
          type: string
        public_jwk:
          type: object
          additionalProperties: true
        attributes:
          type: object
          additionalProperties:
            type: string
          description: Extra attributes to store with the device
        created_at:
          type: string
          format: date-time
        proof:
          type: object
          description: Optional proof summary (ts, nonce, sig hash) for audit
          additionalProperties: true

    EnrollmentBindResponseStatus:
      type: string
      enum: [ BOUND, ALREADY_BOUND ]

    EnrollmentBindResponse:
      type: object
      required: [ status ]
      properties:
        status:
          $ref: '#/components/schemas/EnrollmentBindResponseStatus'
        device_record_id:
          type: string
        bound_user_id:
          type: string

    DeviceDescriptor:
      type: object
      required: [ device_id, jkt, platform, model ]
      properties:
        device_id:
          type: string
        jkt:
          type: string
        public_jwk:
          type: object
          additionalProperties: true
        platform:
          type: string
          examples:
            - ios
        model:
          type: string
        app_version:
          type: string

    UserRecord:
      type: object
      required: [ user_id, username, enabled, email_verified ]
      properties:
        user_id:
          type: string
        realm:
          type: string
        username:
          type: string
        first_name:
          type: string
        last_name:
          type: string
        email:
          type: string
        enabled:
          type: boolean
        email_verified:
          type: boolean
        created_at:
          type: string
          format: date-time
        attributes:
          type: object
          additionalProperties:
            type: string
        custom:
          type: object
          additionalProperties:
            type: [ string, "null" ]

    UserUpsertRequest:
      type: object
      required: [ realm, username ]
      properties:
        realm:
          type: string
        username:
          type: string
        first_name:
          type: string
        last_name:
          type: string
        email:
          type: string
        enabled:
          type: boolean
        email_verified:
          type: boolean
        attributes:
          type: object
          additionalProperties:
            type: string
        custom:
          type: object
          additionalProperties:
            type: [ string, "null" ]

    UserSearchRequest:
      type: object
      required: [ realm ]
      properties:
        realm:
          type: string
        search:
          type: string
        username:
          type: string
        first_name:
          type: string
        last_name:
          type: string
        email:
          type: string
        enabled:
          type: boolean
        email_verified:
          type: boolean
        exact:
          type: boolean
        attributes:
          type: object
          additionalProperties:
            type: string
        first_result:
          type: integer
        max_results:
          type: integer

    UserSearchResponse:
      type: object
      required: [ users ]
      properties:
        users:
          type: array
          items:
            $ref: '#/components/schemas/UserRecord'
        total_count:
          type: integer


    DeviceRecordStatus:
      type: string
      enum: [ ACTIVE, REVOKED, SUSPENDED ]

    DeviceRecord:
      type: object
      required: [ device_id, jkt, status, created_at ]
      properties:
        device_id:
          type: string
        jkt:
          type: string
        status:
          $ref: '#/components/schemas/DeviceRecordStatus'
        created_at:
          type: string
          format: date-time
        last_seen_at:
          type: string
          format: date-time
        device_os:
          type: string
        device_model:
          type: string
        device_app_version:
          type: string
        label:
          type: string

    DeviceLookupRequest:
      type: object
      description: Provide at least one of device_id or jkt
      properties:
        device_id:
          type: string
        jkt:
          type: string

    DeviceLookupResponse:
      type: object
      required: [ found ]
      properties:
        found:
          type: boolean
        user_id:
          type: string
        device:
          $ref: '#/components/schemas/DeviceRecord'
        public_jwk:
          type: object
          additionalProperties: true

    Error:
      type: object
      required: [ code, message ]
      properties:
        code:
          type: string
          examples:
            - bad_request
        message:
          type: string
          examples:
            - Invalid payload
        details:
          type: object
          additionalProperties: true
